openapi: 3.0.3
info:
    title: Notification API
    description: Notification API
    version: "0.1"
servers:
    - url: http://localhost:8000
paths:
    /messages:
        post:
            tags:
                - messages
            summary: send messages
            operationId: messages#send
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/SendRequestBody'
                        example:
                            message: Rerum accusamus culpa impedit officiis in.
            responses:
                "201":
                    description: Created response.
    /messages/subscribe:
        get:
            tags:
                - messages
            summary: subscribe messages
            description: Subscribe to events sent such new chat messages.
            operationId: messages#subscribe
            responses:
                "101":
                    description: Switching Protocols response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/SendRequestBody'
                            example:
                                message: Itaque et magni accusantium fugit voluptatem.
components:
    schemas:
        SendRequestBody:
            type: object
            properties:
                message:
                    type: string
                    example: Non qui amet iure ullam.
            example:
                message: Ut veritatis culpa.
            required:
                - message
tags:
    - name: messages
